# Generated by Django 4.0.3 on 2022-04-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrideGroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('BrideGroom', models.IntegerField(choices=[(0, 'Bride'), (1, 'Groom')])),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('is_child', models.BooleanField()),
                ('in_confirmed', models.BooleanField()),
                ('bridegrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapp.bridegroom')),
            ],
        ),
        migrations.CreateModel(
            name='SeatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_nr', models.IntegerField()),
                ('place_nr', models.IntegerField()),
                ('guests', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weddingapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guests', models.ManyToManyField(to='weddingapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weddingapp.guest')),
            ],
        ),
    ]
